spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db
    username: root
    password: Kau()1933
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
